dudu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("api/", include("todo.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
    path("items/", include("todo_web.urls", namespace="items")),
]

users/urls.py
from django.urls import path

from users.views import UserRegistrationView, SuccessRegistrationView, UserLoginView

app_name = 'users'

urlpatterns = [
    path("success/", SuccessRegistrationView.as_view(), name='success'),
    path("registration/", UserRegistrationView.as_view(), name='registration'),
    path("login/", UserLoginView.as_view(), name='login'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from .managers import UserManager


class UserModel(AbstractUser):
    username = None
    email = models.EmailField(max_length=128, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

users/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError

from .models import UserModel


class UserRegistrationForm(UserCreationForm):
    email = forms.CharField(widget=forms.EmailInput())
    password1 = forms.CharField(widget=forms.PasswordInput(), error_messages={'errors': 'Пароли не совпадают'})
    password2 = forms.CharField(widget=forms.PasswordInput(), error_messages={'error': 'Пароли не совпадают'})

    class Meta:
        model = UserModel
        fields = ('email', 'password1', 'password2')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise ValidationError(
                'Пароли не совпадают',
                code="password_mismatch",
            )
        if len(password1) < 8:
            raise ValidationError(
                'Пароль должен быть больше 8 символов'
            )
        return password2

    def clean(self):
        email = self.cleaned_data.get('email')

        if UserModel.objects.filter(email=email):
            raise ValidationError(
                'Аккаунт с данной почтой уже зарегестрирован',
                code='email',
            )

        return self.cleaned_data


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(), required=False)
    email = forms.CharField(widget=forms.EmailInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(
                self.request, username=email, password=password
            )
            if self.user_cache is None:
                raise ValidationError(
                    'Неверный пароль'
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data.get('email')

        user = UserModel.objects.filter(email=email)
        if not user:
            raise ValidationError(
                'Аккаунта с такой почтой не существует'
            )
        return email

    class Meta:
        model = UserModel
        fields = ('email', 'password')

users/views.py
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy

from .models import UserModel
from .forms import UserRegistrationForm, UserLoginForm


class UserRegistrationView(CreateView):
    model = UserModel
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')


class SuccessRegistrationView(TemplateView):
    template_name = 'users/success_page.html'


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

users/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome!</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style_login.css' %}">

</head>
<body>
    <div class="container-fluid ps-md-0">
        <div class="row g-0">
            <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
            
            <div class="col-md-8 col-lg-6">
                <div class="login d-flex align-items-center py-5">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-9 col-lg-8 mx-auto">
                                <h3 class="login-heading mb-4">Добро пожаловать!</h3>
                                
                                <form action="{% url 'users:login' %}" method="post">
                                    {% csrf_token %}
                                    
                                    <div class="form-floating mb-3">
                                        {{ form.email }}
                                        <label for="{{ form.email.auto_id }}">Email адрес</label>
                                        <script>
                                            document.getElementById("{{ form.email.auto_id }}").setAttribute("placeholder", "name@example.com");
                                        </script>
                                    </div>
                                
                                    <div class="form-floating mb-3">
                                        {{ form.password }}
                                        <label for="{{ form.password.auto_id }}">Пароль</label>
                                        <script>
                                            document.getElementById("{{ form.password.auto_id }}").setAttribute("placeholder", "Password");
                                        </script>
                                    </div>

                                    <div class="form-check mb-3">
                                        <input class="form-check-input" type="checkbox" value="" id="rememberPasswordCheck">
                                        <label class="form-check-label" for="rememberPasswordCheck">
                                        Запомнить пароль
                                        </label>
                                    </div>
                                
                                    <div class="d-grid">
                                        <button class="btn btn-lg btn-custom text-uppercase fw-bold mb-2" type="submit">Войти</button>
                                    </div>
                                    
                                    <div class="text-center">
                                        <a class="small" href="#">Забыли пароль?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'users:registration' %}">Зарегистрироваться</a>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>      
</body>
</html>

users/templates/users/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style_register.css' %}">
    
</head>
<body>
  <div class="container">
    <div class="row">
        <div class="col-lg-10 col-xl-9 mx-auto">
            <div class="card flex-row my-5 border-0 shadow rounded-3 overflow-hidden">
              <div class="card-img-left d-none d-md-flex">
                  
              </div>
                <div class="card-body p-4 p-sm-5">
                    <h5 class="card-title text-center mb-5 fw-light fs-5">Регистрация</h5>
                    <form action="{% url 'users:registration' %}" method="post">
                              {% csrf_token %}
                        
                        <!-- Отображение ошибок -->
                              {% if form.non_field_errors %}
                                  {{ form.non_field_errors.0 }}
                              {% elif form.password2.errors %}
                                  {{ form.password2.errors.0}}
                              {% endif %}

                        <!-- Поля формы -->
                        <div class="form-floating mb-3">
                              {{ form.email }}
                              <label for="{{ form.email.auto_id }}">Email адрес</label>
                              <script>
                                  document.getElementById("{{ form.email.auto_id }}").setAttribute("placeholder", "name@example.com");
                              </script>
                        </div>

                        <hr>
                  
                        <div class="form-floating mb-3">
                              {{ form.password1 }}
                              <label for="{{ form.password1.auto_id }}">Пароль</label>
                              <script>
                                  document.getElementById("{{ form.password1.auto_id }}").setAttribute("placeholder", "Password");
                              </script>
                        </div>
                  
                        <div class="form-floating mb-3">
                              {{ form.password2 }}
                              <label for="{{ form.password2.auto_id }}">Повторите пароль</label>
                              <script>
                                  document.getElementById("{{ form.password2.auto_id }}").setAttribute("placeholder", "Confirm Password");
                              </script>
                        </div>
                  
                        <div class="d-grid mb-2">
                                <button class="btn btn-lg btn-custom text-uppercase fw-bold mb-2" type="submit">Зарегистрироваться</button>
                        </div>

                        <a class="d-block text-center mt-2 small" href="{% url 'users:login' %}">У вас есть учетная запись? войти в систему</a>

                        <hr class="my-4">

                        <div class="d-grid mb-2">
                                <button class="btn btn-lg btn-google btn-login fw-bold text-uppercase" type="submit">
                                  <i class="fab fa-google me-2"></i> Sign up with Google
                                </button>
                        </div>
                        
                        <div class="d-grid mb-2">
                                <button class="btn btn-lg btn-vk btn-login fw-bold text-uppercase" type="submit">
                                  <i class="fab fa-vk me-2"></i> Sign up with VK
                                </button>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

users/templates/users/success_page.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DuDu</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>

  <div class="left-menu">
    <div class="logo" alt = "DuDu">
    </div>
    <div class = "logo-title">DuDu</div>
    <ul class="menu-list">
      <li><a href="#user">User</a></li>
      <li><a href="#my-tasks">Мои задачи</a></li>
      <li><a href="#settings">Настройки</a></li>
      <li><a href="#help">Помощь/FAQ</a></li>
      <li><a href="#exit">Выход</a></li>
    </ul>
  </div>

  <div class="container mt-4">
    <h2>Список задач</h2>
    <table class="table">
      <thead>
        <tr>
            <th>Готовность</th>
            <th>Название</th>
            <th>Описание</th>
            <th>Срок</th>
            <th>Приоритет</th>
            <th>Тег</th>
            <th>Действия</th>
        </tr>
    </thead>
      <tbody id="taskTableBody">
        <!-- Здесь будут добавляться строки задач -->
      </tbody>
    </table>
    <!-- Кнопка для добавления новой задачи -->
    <button class="btn btn-primary mb-3" onclick="addTask()">Добавить задачу</button>

    <script src="{% static 'js/script.js' %}"></script>
  </div>
</body>

</html>